(define (make-account balance pw)
  (define (withdraw amount pw-input)
    (if (eq? pw pw-input)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance)
            "Insufficient funds")
        "Incorrect password"))
  (define (deposit amount pw-input)
    (if (eq? pw pw-input)
        (begin (set! balance (+ balance amount))
               balance)
        "Incorrect password"))
  (define (dispatch m pw-input)
    (if (eq? pw pw-input)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT"
                       m)))
        "Incorrect password"))
  dispatch)