(define (element-of-set? x set)
  (cond ((null? set) false)
        ((= x (car set)) true)
        ((< x (car set)) false)
        (else (element-of-set? x (cdr set)))))

(define (intersection-set set1 set2)
  (if (or (null? set1) (null? set2))
      '()
      (let ((x1 (car set1)) (x2 (car set2)))
        (cond ((= x1 x2)
               (cons x1 (intersection-set (cdr set1)
                                          (cdr set2))))
              ((< x1 x2)
               (intersection-set (cdr set1) set2))
              ((< x2 x1)
               (intersection-set set1 (cdr set2)))))))

(define (adjoin x set)
  (define (adjoin-iter x set1 set2)
    (cond ((null? set2)
           (append set1 (list x)))
          ((= x (car set2))
           (append set1 set2))
          ((< x (car set2))
           (append set1 (list x) set2))
          (else (adjoin-iter x
                             (append set1 (list (car set2)))
                             (cdr set2)))))
  (adjoin-iter x '() set))

; implementation
(define (union-set set1 set2)
  (define (union-set-iter s b acc)
    (cond ((null? s)
            (append acc b))
           ((< (car s) (car b))
            (union-set-iter (cdr s) b (append acc (list (car s)))))
           (else (append acc b))))
  (cond ((null? set1) set2)
        ((null? set2) set1)
        ((< (car set1) (car set2))
         (union-set-iter set1 set2 '()))
        (else (union-set-iter set2 set1 '()))))

; tests
(union-set '(1 2 3 4 5) '(4 5 6 7))
(union-set '(1 2) '(5 6 7))
(union-set '(1 2 3 4 5) '())
(union-set '() '(4 5 6 7))